name: CI

on:
  push:
    branches: ["master"]

jobs:
  run:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
      - run: flutter run -d macos --debug


